jsf2_spring_conversation_bank/src/main/generated-java/com/jaxio/jsf2_spring_conversation_bank/domain/Role.java
/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/domain/Entity.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.jaxio.jsf2_spring_conversation_bank.domain;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.search.annotations.Analyzer;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Indexed;
import org.hibernate.validator.constraints.NotEmpty;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import com.jaxio.jpa.querybyexample.Identifiable;

@Entity
@Table(name = "`ROLE`")
@Indexed
public class Role implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(Role.class);

    // Raw attributes
    private Integer id;
    private String roleName;

    // -- [id] ------------------------

    @Override
    @Column(name = "ID", precision = 10)
    @GeneratedValue
    @Id
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public Role id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return id != null;
    }

    // -- [roleName] ------------------------

    @NotEmpty
    @Size(max = 100)
    @Column(name = "ROLE_NAME", nullable = false, unique = true, length = 100)
    @Field(analyzer = @Analyzer(definition = "custom"))
    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public Role roleName(String roleName) {
        setRoleName(roleName);
        return this;
    }

    /**
     * Apply the default values.
     */
    public Role withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Role && hashCode() == other.hashCode());
    }

    private volatile int previousHashCode = 0;

    @Override
    public int hashCode() {
        int hashCode = Objects.hashCode(getRoleName());

        if (previousHashCode != 0 && previousHashCode != hashCode) {
            log.warn("DEVELOPER: hashCode has changed!." //
                    + "If you encounter this message you should take the time to carefully review equals/hashCode for: " //
                    + getClass().getCanonicalName());
        }

        previousHashCode = hashCode;
        return hashCode;
    }

    /**
     * Construct a readable string representation for this Role instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("roleName", getRoleName()) //
                .toString();
    }
}

jsf2_spring_conversation_bank/src/main/webapp/WEB-INF/taglib/panel/edit.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:app="http://jaxio.com/app"
	xmlns:p="http://primefaces.org/ui"
	template="/WEB-INF/layouts/#{print ? 'print' : 'main'}.xhtml">
	<ui:define name="toolbarChildren">
		<p:toolbarGroup>
			<p:commandButton id="print" value="#{msg.menu_print}" action="#{bean.print()}" rendered="#{bean.entity.idSet}"
				icon="ui-icon-print" immediate="true" ajax="false" />
		</p:toolbarGroup>
		<p:toolbarGroup rendered="#{sub or readonly}">
			<p:commandButton id="back" action="#{bean.back()}" process="@none" ajax="false" immediate="true"
				value="#{msg.back}" icon="ui-icon-arrowreturnthick-1-w" />
		</p:toolbarGroup>
		<p:toolbarGroup rendered="#{not sub and not readonly}">
			<p:commandButton id="close" oncomplete="PF('askForSaveDialog').show(); APP.focusAskForSaveDialog();"
				ajax="true" immediate="true" process="@this"
				icon="ui-icon-close"
				value="#{msg.menu_close}"
				title="#{msg.menu_close} #{resourcesUtil.getProperty(title)}"/>
			<p:commandButton id="delete" icon="ui-icon-trash"
				onclick="PF('askForDeleteDialog').show(); APP.focusAskForDeleteDialog();"
				value="#{msg.menu_delete_and_close}"
				title="#{msg.menu_delete_and_close} #{resourcesUtil.getProperty(title)}"
				disabled="#{empty bean.entity.id}"
				rendered="#{permission.canDelete(bean.entity)}" />
			<p:separator />
		</p:toolbarGroup>
	</ui:define>
	<ui:define name="content">
		<p:breadCrumb model="#{conversationBreadCrumb.model}" rendered="#{conversationBreadCrumb.render}" />
		<p:fieldset id="fieldset">
			<input type="hidden" name="_cid" value="#{conversationManager.currentConversation.cid}"/>
			<f:validateBean disabled="true">
				<h:panelGrid columns="2" styleClass="aria-role-presentation">
					<ui:insert name="form" />
				</h:panelGrid>
				<app:saveButton title="#{title}" bean="#{bean}"/>
			</f:validateBean>
		</p:fieldset>
		<p:tabView id="tabs" activeIndex="#{bean.tabBean.activeIndex}" rendered="#{not empty bean.tabBean and not print}">
			<p:ajax event="tabChange" />
			<ui:insert name="tabs"/>
		</p:tabView>
		<p:accordionPanel id="tabsPrint" activeIndex="0,1,2,3,4,5,6,7,8,9,10" cache="false" multiple="true" 
			rendered="#{not empty bean.tabBean and print}">
			<ui:insert name="tabs"/>
		</p:accordionPanel>
	</ui:define>
	<ui:define name="dialogs">
		<ui:insert name="custom-dialogs" />
		<p:confirmDialog widgetVar="askForDeleteDialog" header="#{msg.menu_delete}?" message="#{msg.dialog_delete_confirm}">
			<h:panelGrid id="askForDeleteDialogContent" columns="1" cellpadding="4" style="margin:0 auto;">
				<h:outputText value="#{printer.print(bean.entity)}" style="font-weight:bold" />
			</h:panelGrid>
			<p:commandButton id="askForDeleteDialogYes" action="#{bean.deleteAndClose()}" ajax="false" immediate="true" process="@none" value="#{msg.yes}" title="#{msg.dialog_delete_confirm} #{msg.yes}" icon="ui-icon-check" />
			<p:commandButton id="askForDeleteDialogNo" value="#{msg.no}" title="#{msg.dialog_delete_confirm} #{msg.no}" onclick="PF('askForDeleteDialog').hide(); APP.focusTo('form:delete'); return false;" icon="ui-icon-cancel"/>
		</p:confirmDialog>
		<p:confirmDialog widgetVar="askForSaveDialog" header="#{msg.menu_save}?" message="#{msg.dialog_ask_for_save}">
			<p:commandButton id="askForSaveDialogYes" action="#{bean.saveAndClose()}" ajax="true" process="@form" value="#{msg.yes}"
				title="#{msg.dialog_ask_for_save} #{msg.yes}"
				onstart="PF('askForSaveDialog').hide()"
				styleClass="aria-save-button"
				update="messages" icon="ui-icon-check" />
			<p:commandButton id="askForSaveDialogNo" action="#{bean.forceClose()}" ajax="false"
				value="#{msg.no}"
				title="#{msg.dialog_ask_for_save} #{msg.no}"
				icon="ui-icon-cancel" immediate="true" process="@none" />
		</p:confirmDialog>
	</ui:define>
</ui:composition>

jsf2_spring_conversation_bank/src/main/webapp/WEB-INF/taglib/panel/search.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:app="http://jaxio.com/app"
	xmlns:p="http://primefaces.org/ui"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	template="/WEB-INF/layouts/main.xhtml">
	<ui:define name="toolbarChildren">
		<p:toolbarGroup rendered="#{sub or readonly}">
			<p:commandButton id="back" action="#{searchForm.back()}" process="@none" ajax="false" immediate="true"
				value="#{msg.back}" icon="ui-icon-arrowreturnthick-1-w"/>
		</p:toolbarGroup>
		<p:toolbarGroup align="left" rendered="#{not sub and not readonly}">
			<p:commandButton id="quit" action="#{searchForm.quit()}" ajax="false" immediate="true" process="@form"
				icon="ui-icon-closethick"
				value="#{msg.menu_quit}"
				title="#{msg.menu_quit} #{resourcesUtil.getProperty(title)}" />
			<p:separator />
			<p:commandButton id="create" action="#{model.create()}" ajax="false" immediate="true" process="@this"
				icon="ui-icon-document"
				rendered="#{empty bean and permission.canCreate()}"
				value="#{msg.menu_new}"
				title="#{msg.menu_new} #{resourcesUtil.getProperty(title)}" />
		</p:toolbarGroup>
	</ui:define>
	<ui:define name="content">
		<p:breadCrumb model="#{conversationBreadCrumb.model}" rendered="#{conversationBreadCrumb.render}" />
		<p:fieldset id="fullTextFieldset" legend="#{msg.search_full_text_criteria}" toggleable="true" rendered="#{fullText}">
			<h:panelGrid columns="4">
				<ui:insert name="fullTextFilters" />
			</h:panelGrid>
		</p:fieldset>
		<p:fieldset id="filtersFieldset" legend="#{msg.search_criteria}" toggleable="true">
			<input type="hidden" name="_cid" value="#{conversationManager.currentConversation.cid}"/>
			<f:validateBean disabled="true">
				<h:panelGrid columns="4">
					<ui:insert name="filters" />
				</h:panelGrid>
			</f:validateBean>
		</p:fieldset>
		<p:commandButton id="search" actionListener="#{model.onSearch()}" process="@form"
			icon="iconSearch" styleClass="aria-search-button default"
			update="messages searchResults" value="#{msg.menu_search}"
			title="#{msg.menu_search} #{resourcesUtil.getProperty(title)}" />
		<p:commandButton id="resetSearch" icon="ui-icon-power" value="#{msg.search_reset}"
			actionListener="#{searchForm.reset()}"
			update="messages fullTextFieldset filtersFieldset searchResults searchFormName"/>
		<p:commandButton id="excel" action="#{model.onExcel()}" process="@form"
			icon="iconExcel" value="Excel" ajax="false" />
		<h:panelGroup rendered="#{savedSearch}">
			<p:autoComplete id="searchFormName" rendered="#{savedSearch}"
				value="#{searchForm.currentSavedSearch}"
				completeMethod="#{savedSearchService.finderFor(searchForm).find}"
				var="item" itemValue="#{item}" itemLabel="#{savedSearchPrinter.print(item)}" converter="#{genericJsfConverter}"
				dropdown="true" size="30">
				<p:ajax event="itemSelect" update="fullTextFieldset filtersFieldset messages searchResults searchFormName" />
			</p:autoComplete>
			<p:commandButton id="displaySavedSearchPanel" rendered="#{savedSearch}" icon="ui-icon-disk" />
			<p:overlayPanel id="savedSearchPanel" widgetVar="savedSearchPanel" for="displaySavedSearchPanel" hideEffect="fade" dynamic="false">
				<h:panelGrid columns="2" styleClass="aria-role-presentation">
					<app:input id="savedSearchName" value="#{searchForm.searchFormName}" label="savedSearch_name" required="true" />
					<app:inputBoolean id="savedSearchPrivate" label="savedSearchName_private" value="#{searchForm.privateSearch}" />
				</h:panelGrid>
				<h:panelGroup>
					<p:commandButton id="saveSearch" actionListener="#{savedSearchService.save(searchForm)}" process="@form"
						icon="ui-icon-disk" update="fullTextFieldset filtersFieldset messages searchResults savedSearchPanel"
						value="#{msg.search_save}" />
				</h:panelGroup>
			</p:overlayPanel>
		</h:panelGroup>
		<ui:insert name="buttons" />
		<br />
		<span style="height: 16px; display: block;">
			<p:ajaxStatus>
				<f:facet name="start">
					<h:graphicImage id="ajaxSearchLoading" name="icons/ajaxloading.gif" alt="Loading..." />
				</f:facet>
				<f:facet name="error">
					<h:outputText id="ajaxSearchError" value="#{msg.error_ajax}" />
				</f:facet>
				<f:facet name="success">
					<h:outputText id="ajaxSearchSuccess" value="" />
				</f:facet>
			</p:ajaxStatus>
		</span>
		<!-- safari/voiceover requires 'span' (not 'div') for live region-->
		<span id="searchResultsRegion" aria-label="#{msg.search_results}" aria-live="assertive" aria-relevant="additions">
		</span>
		<c:if test="#{empty multiCheckboxSelection or not multiCheckboxSelection}">
			<p:dataTable id="searchResults"
				value="#{model}" var="item" lazy="true"
				paginator="true" paginatorAlwaysVisible="false" paginatorPosition="bottom"
				rowsPerPageTemplate="10,25,50,100" rows="10"
				selectionMode="single" selection="#{model.selectedRow}"
				emptyMessage="#{msg.search_empty}">
				<ui:insert name="result" />
			</p:dataTable>
		</c:if>
		<c:if test="#{not empty multiCheckboxSelection and multiCheckboxSelection}">
			<p:dataTable id="searchResults"
				value="#{model}" var="item" lazy="true"
				paginator="true" paginatorAlwaysVisible="false" paginatorPosition="bottom"
				rowsPerPageTemplate="10,25,50,100" rows="10"
				selection="#{model.selectedRows}"
				emptyMessage="#{msg.search_empty}">
				<p:column id="selectAll" selectionMode="multiple" style="width:18px" rendered="#{permission.canSelect()}" />
				<ui:insert name="result" />
				<f:facet name="footer">
					<app:iconMultiSelect model="#{model}" rendered="true" process="@this" />
				</f:facet>
			</p:dataTable>
		</c:if>
		<script type="text/javascript">APP.updateSearchResultsRegion('#{resourcesUtil.getPluralableProperty("search_results_status", model.rowCount)}', #{model.rowCount});</script>
	</ui:define>
	<ui:define name="dialogs">
		<p:confirmDialog widgetVar="askForDeleteItemDialog" header="#{msg.menu_delete}?" message="#{msg.dialog_delete_confirm}">
			<h:panelGrid id="askForDeleteItemDialogContent" columns="2" cellpadding="4" style="margin:0 auto;">
				<h:outputText value="#{printer.print(model.selectedRow)}" style="font-weight:bold" rendered="#{not empty model.selectedRow}"/>
			</h:panelGrid>
			<p:commandButton id="askForDeleteItemDialogYes" action="#{model.delete()}" ajax="true" immediate="true" oncomplete="PF('askForDeleteItemDialog').hide();" process="@this" value="#{msg.yes}" title="#{msg.dialog_delete_confirm} #{msg.yes}" icon="ui-icon-check" update=":form:searchResults :form:messages"/>
			<p:commandButton id="askForDeleteItemDialogNo" value="#{msg.no}" title="#{msg.dialog_delete_confirm} #{msg.no}" onclick="PF('askForDeleteItemDialog').hide(); return false;" icon="ui-icon-cancel"/>
		</p:confirmDialog>
	</ui:define>
</ui:composition >